ipc = on
splash = false

preload = /home/ste/Downloads/borderlands-4-5120x2880-22442.jpg

wallpaper {
    monitor = eDP-1
     path = /home/ste/Downloads/borderlands-4-5120x2880-22442.jpg
    fit_mode = cover
}

