# ~/.config/matugen/templates/hyprtoolkit.toml

[theme]
# CC adds ~80% transparency to the background elements
bg = 0xCC1a1110
base = 0xCC1a1110
# FF keeps text completely solid and highly readable
text = 0xFFf1dedc
accent = 0xFFffb4a9
secondary_accent = 0xFFe7bdb7

[font]
family = "Sans-Serif"
monospace = "JetBrainsMono Nerd Font"
size_text = 13
size_h1 = 18

[icons]
theme = "Papirus-Dark"

