[config]
theme_mode = "dark"

[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland.conf"
output_path = "~/.config/hypr/colors.conf"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty.conf"
output_path = "~/.config/kitty/colors.conf"

[templates.hyprlauncher]
input_path = '~/.config/matugen/templates/hyprtoolkit.toml'
output_path = '~/.config/hypr/hyprtoolkit.conf'

