# ~/.config/matugen/templates/hyprtoolkit.toml

[theme]
# CC adds ~80% transparency to the background elements
bg = 0xCC{{colors.background.default.hex_stripped}}
base = 0xCC{{colors.surface.default.hex_stripped}}
# FF keeps text completely solid and highly readable
text = 0xFF{{colors.on_background.default.hex_stripped}}
accent = 0xFF{{colors.primary.default.hex_stripped}}
secondary_accent = 0xFF{{colors.secondary.default.hex_stripped}}

[font]
family = "Sans-Serif"
monospace = "JetBrainsMono Nerd Font"
size_text = 13
size_h1 = 18

[icons]
theme = "Papirus-Dark"

