foreground #{{colors.on_background.default.hex_stripped}}
background #{{colors.background.default.hex_stripped}}
color0     #{{colors.surface.default.hex_stripped}}
color1     #{{colors.error.default.hex_stripped}}
color2     #{{colors.primary.default.hex_stripped}}

